### ISSUE TITLE
It seems mod doesn't wont to work with Russian language

### ISSUE THREAD

**Issue by ScrewBanger** [pixeldesu/Cloudburst#6]
I'am sorry, can this be fixed? I don’t know much about this, but I would really like to play with this mod.
I have already seen a similar problem with non-English languages, in a issues, but i really don't know how ti fix it

Here is the error in the console:

```
[Info   :   BepInEx] Loading [Pingprovements 1.5.1]
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.Single.Parse (System.String s) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
Pingprovements.Extensions.ToColor (System.String colorString) (at <2c90838e5b43455a9dddee7f0b2d3518>:0)
Pingprovements.PingerController..ctor (Pingprovements.Pingprovements plugin) (at <2c90838e5b43455a9dddee7f0b2d3518>:0)
Pingprovements.Pingprovements.Awake () (at <2c90838e5b43455a9dddee7f0b2d3518>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.SkinDef:Awake()
```

**Comment by pixeldesu** [comment]
I built the changes from PR #5 into a mod. I tried replicating the issue on my system switching to Russian or other languages but I never got the error.

Build of #5: [Pingprovements.zip](https://github.com/pixeldesu/Cloudburst/files/4638545/Pingprovements.zip)

Could you try running this build on your system and verify that the error doesn't appear anymore? If you leave me feedback, I can properly build and release it on Thunderstore afterwards, if it works!

**Comment by ScrewBanger** [comment]
Yeah, i tested it and now it is working correctly. Thanks!
